### ISSUE TITLE
Articulate funding trade-offs

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/travel-modeling-as-science#6]
Specifically: 
- What are the issues potential funders would trade-off to invest in this approach as opposed to the status quo? 
- What are the pros and cons from different perspectives, e.g., the Feds, the States, the MPOs, researchers.

**Comment by e-lo** [comment]
@DavidOry - do you think this would go in [ B-Business Plan](https://github.com/MetropolitanTransportationCommission/travel-modeling-as-science/blob/master/B-business-plan.md) ?

**Comment by DavidOry** [comment]
I think so.  You've identified potential customers.  I would benefit from reading the value proposition to each customer relative to the status quo.
